In [1]:
import numpy as np
import pandas as pd

/home/brian/.virtualenvs/this/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)


In [8]:
df = pd.read_csv('meta.csv')
df['time'] = df.months
df.head()

id  months  event  metastized  time
0   1       5   True        True     5
1   2       8   True        True     8
2   3      10   True        True    10
3   4      13   True        True    13
4   5      18   True        True    18

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 4 columns):
id            44 non-null int64
months        44 non-null int64
event         44 non-null bool
metastized    44 non-null bool
dtypes: bool(2), int64(2)
memory usage: 872.0 bytes


In [54]:
n_patients = df.shape[0]
patients = np.arange(n_patients)
df['patient'] = patients

In [56]:
interval_length = 3
interval_bounds = np.arange(0, df.time.max() + interval_length + 1, interval_length)
interval_bounds

array([  0,   3,   6,   9,  12,  15,  18,  21,  24,  27,  30,  33,  36,
        39,  42,  45,  48,  51,  54,  57,  60,  63,  66,  69,  72,  75,
        78,  81,  84,  87,  90,  93,  96,  99, 102, 105, 108, 111, 114,
       117, 120, 123, 126, 129, 132, 135, 138, 141, 144, 147, 150, 153,
       156, 159, 162, 165, 168, 171, 174, 177, 180, 183, 186, 189, 192,
       195, 198, 201, 204, 207, 210, 213, 216, 219, 222, 225, 228])

In [57]:
n_intervals = interval_bounds.size - 1
intervals = np.arange(n_intervals)
intervals

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75])

In [61]:
last_period = np.floor((df.time - 0.01) / interval_length).astype('int')
df['last_period'] = last_period
df['last_period_lower'] = interval_bounds[df.last_period]
df

id  months  event  metastized  time  patient  last_period  \
0    1       5   True        True     5        0            1   
1    2       8   True        True     8        1            2   
2    3      10   True        True    10        2            3   
3    4      13   True        True    13        3            4   
4    5      18   True        True    18        4            5   
5    6      23   True       False    23        5            7   
6    7      24   True        True    24        6            7   
7    8      26   True        True    26        7            8   
8    9      26   True        True    26        8            8   
9   10      31   True        True    31        9           10   
10  11      35   True        True    35       10           11   
11  12      40   True        True    40       11           13   
12  13      41   True        True    41       12           13   
13  14      47   True       False    47       13           15   
14  15      48   True        True    48       14           15   
15  16      50   True        True    50       15           16   
16  17      59   True        True    59       16           19   
17  18      61   True        True    61       17           20   
18  19      68   True        True    68       18           22   
19  20      69   True       False    69       19           22   
20  21      70  False       False    70       20           23   
21  22      71   True        True    71       21           23   
22  23      76  False        True    76       22           25   
23  24     100  False       False   100       23           33   
24  25     101  False       False   101       24           33   
25  26     105  False        True   105       25           34   
26  27     107  False        True   107       26           35   
27  28     109  False        True   109       27           36   
28  29     113   True        True   113       28           37   
29  30     116  False        True   116       29           38   
30  31     118   True        True   118       30           39   
31  32     143   True        True   143       31           47   
32  33     145  False        True   145       32           48   
33  34     148   True       False   148       33           49   
34  35     162  False        True   162       34           53   
35  36     181   True       False   181       35           60   
36  37     188  False        True   188       36           62   
37  38     198  False       False   198       37           65   
38  39     208  False       False   208       38           69   
39  40     212  False       False   212       39           70   
40  41     212  False        True   212       40           70   
41  42     217  False        True   217       41           72   
42  43     224  False       False   224       42           74   
43  44     225  False        True   225       43           74   

    last_period_lower  
0                   3  
1                   6  
2                   9  
3                  12  
4                  15  
5                  21  
6                  21  
7                  24  
8                  24  
9                  30  
10                 33  
11                 39  
12                 39  
13                 45  
14                 45  
15                 48  
16                 57  
17                 60  
18                 66  
19                 66  
20                 69  
21                 69  
22                 75  
23                 99  
24                 99  
25                102  
26                105  
27                108  
28                111  
29                114  
30                117  
31                141  
32                144  
33                147  
34                159  
35                180  
36                186  
37                195  
38                207  
39                210  
40                210  
41                216  
42                222  
43                222

In [62]:
death = np.zeros((n_patients, n_intervals))
death[patients, last_period] = df.event.astype('int')
death[4,:]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [63]:
exposure = np.greater_equal.outer(df.time, interval_bounds[:-1]) * interval_length
exposure[patients, last_period] = df.time - interval_bounds[last_period]
exposure[4,:]

array([3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [39]:
exposure[4,:]

array([3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [30]:
df[df.id == 5]

id  months  event  metastized  time  patient
4   5      18   True        True    18        4

In [42]:
death[4,:]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
last_period[4]

5

In [36]:
intervals

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75])